routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('companies', 'CompaniesController');
Route::resource('projects', 'ProjectsController');
Route::resource('roles', 'RolesController');
Route::resource('task', 'TasksController');
Route::resource('companies', 'CompaniesController');
Route::resource('users', 'UsersController');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable = [
        'name',
        'description',
        'user_id'
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function projects() {
        return $this->hasMany('App\Project');
    }
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = Company::all();

        return view('companies.index', ['companies'=> $companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
        // $company = Company::where('id', $company->id)->first();
        $company = Company::find($company->id);

        return view('companies.show', ['company'=> $company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
        $company = Company::find($company->id);

        return view('companies.edit', ['company'=> $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        // Save Data
        $companyUpdate = Company::where('id', $company->id)
            ->update([
                'name'=> $request->input('name'),
                'description'=> $request->input('description')
            ]);
        if($companyUpdate) {
            return redirect()->route('companies.show', ['company'=>$company->id])->with('success', 'Company updated successfuly');
        }
        // Redirect
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
        $findCompany = Company::find($company->id);
        if($findCompany->delete()) {
            // Redirect
            return redirect()->route('companies.index')->with('success', 'Company deleted successfully!');
        }
        return back()->withInput()->with('error', 'Company could not be deleted');
    }
}

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <!-- Projects -->
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-12">
                        <form method="POST" action="{{ route('companies.update', [$company->id]) }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="form-group">
                                <label for="company-name">Name<span class="required">*</span></label>
                                <input type="text"
                                    required
                                    class="form-control"
                                    id="company-name"
                                    name="name"
                                    spellcheck="false"
                                    placeholder="Enter Company Name"
                                    value="{{ $company->name }}">
                            </div>
                            <div class="form-group">
                                <label for="company-description">Description</label>
                                <textarea style="resize: vertical"
                                    class="form-control"
                                    id="company-description"
                                    name="description"
                                    rows="5"
                                    spellcheck="false"
                                    placeholder="Enter Company Description">{{ $company->description }}
                                </textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Submit" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <!-- Sidebar -->
            <aside class="col-md-4">
                <div class="p-3">
                    <h4>Options</h4>
                    <ol class="list-unstyled mb-0">
                    <li><a href="/companies/{{ $company->id }}">View Company</a></li>
                        <li><a href="/companies">List Comapnies</a></li>
                    </ol>
                </div>

            {{-- <div class="p-3">
                <h4 class="font-italic">Members</h4>
                <ol class="list-unstyled">
                    <li><a href="#">User 1</a></li>
                </ol>
            </div> --}}
            </aside>
        </div>
    </div> <!-- /container -->
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card" style="width: 18rem;">
        <div class="card-header bg-success">
        Companies
        </div>
        <ul class="list-group list-group-flush">
        @foreach ($companies as $company)
        <li class="list-group-item"><a href="/companies/{{ $company->id }}">{{ $company->name }}</a></li>
        @endforeach
        </ul>
    </div>
</div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-3">{{ $company->name }}</h1>
            <p>{{ $company->description }}</p>
            {{-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p> --}}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <!-- Projects -->
            <div class="col-md-8">
                <div class="row">
                    @foreach ($company->projects as $project)
                    <div class="col-md-6">
                        <h2>{{ $project->name }}</h2>
                        <p>{{ $project->description }}</p>
                        <p><a class="btn btn-secondary" href="/project/{{ $project->id }}" role="button">View project »</a></p>
                    </div>
                    @endforeach
                </div>
            </div>

            <!-- Sidebar -->
            <aside class="col-md-4">
                <div class="p-3">
                    <h4>Options</h4>
                    <ol class="list-unstyled mb-0">
                    <li><a href="/companies/{{ $company->id }}/edit">Edit</a></li>
                    <li><a href="/projects/create">Add Project</a></li>
                    <hr>
                    <li>
                        <a href="#"
                            onclick="
                                var result = confirm('Are you sure you wish to delete this company?');
                                if(result) {
                                    event.preventDefault();
                                    document.getElementById('delete-form').submit();
                                }
                            ">Delete
                        </a>

                        <form id="delete-form"
                            action="{{ route('companies.destroy', [$company->id]) }}"
                            method="POST"
                            style="display:none;">
                            <input type="hidden" name="_method" value="delete" />
                            {{ csrf_field() }}
                        </form>
                    </li>
                    </ol>
                </div>
            </aside>
        </div>
    </div> <!-- /container -->
@endsection